name: Build MT3000

on:
  push:
    paths:
      - '.github/workflows/MT3000.yml'
      
env:
  REPO_URL: https://github.com/gl-inet/gl-infra-builder
  REPO_BRANCH: master
  TZ: Asia/Shanghai
  NAME: MT3000_glinet
  # true
  SSH: false
  MAKECONFIG: false
  NGROK_TOKEN: ${{ secrets.NGROK_TOKEN_1 }}
  USER_PASS: ${{ secrets.USER_PASS_1 }}
  PLARFORM: mt7981
  CONFIG: config-mt798x-7.6.6.1.yml
  GL_PKG_CONFIG: gl_pkg_config_mt3000.mk
  GLINET_DEPENDS: glinet_depends_mt3000.yml
  
jobs:
  build:
    #runs-on: ubuntu-latest 
    runs-on: ubuntu-20.04
    # runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
       
    - name: Start SSH via Ngrok
      if: env.SSH == 'true'
      run: |
        curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
      env:
        # After sign up on the https://ngrok.com/ 
        # You can find this token here: https://dashboard.ngrok.com/get-started/setup
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN_2 }}
        # This password you will use when authorizing via SSH
        USER_PASS: ${{ secrets.USER_PASS_2 }}
        
    - name: Initialization environment
    # sudo -E apt-get install git  asciidoc bash bc binutils bzip2 fastjar flex gawk gcc genisoimage gettext git intltool jikespg libgtk2.0-dev libncurses5-dev libssl-dev make mercurial patch perl-modules python2.7-dev rsync ruby sdcc subversion unzip util-linux wget xsltproc zlib1g-dev zlib1g-dev -y
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get update
        sudo -E apt-get -qq install build-essential libncurses5-dev gawk git libssl-dev \
            gettext zlib1g-dev swig unzip time rsync python3 python3-setuptools python3-yaml \
            libp11-kit-dev clang flex bison g++ gcc-multilib g++-multilib python3-distutils file wget qemu-utils
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
    
    - name:  git clone gl-infra-builder
      id: gitclone
      run: |
         git clone https://github.com/gl-inet/gl-infra-builder.git && cd gl-infra-builder
         git config --global user.email 'youremail.com'
         git config --global user.name 'name'

    - name:  list the openwrt verizon
      run: |
         cd gl-infra-builder
         ls configs -hl
    
    - name:  git checkout1
      run: |
        cd gl-infra-builder
        git checkout v4.2.0_mt3000_release1
       
    - name: config-mt798x-7.6.6.1.yml
      run: |
         cd gl-infra-builder
         python3 setup.py -c configs/$CONFIG
         
    - name: 编译 make manuconfig
      if: env.MAKECONFIG == 'true' 
     #  make manuconfig
      run: |
        cd gl-infra-builder/$PLARFORM
        sleep 3h
        
    - name:  gen_config.py glinet_depends
       #     cp ./glinet4.x/pkg_config/glinet_depends_mt3000.yml  ./profiles/glinet_depends.yml     && \
      run: |
        df -h
        cd gl-infra-builder/$PLARFORM
        git clone https://github.com/gl-inet/glinet4.x.git && \
            cp ./glinet4.x/pkg_config/$GL_PKG_CONFIG  ./glinet4.x/$PLARFORM/gl_pkg_config.mk && \
            cp ./glinet4.x/pkg_config/$GLINET_DEPENDS  ./profiles/glinet_depends.yml && \
            ./scripts/gen_config.py glinet_depends
            
        
    - name: 查看 .config 
      run: |
        df -h
        cd gl-infra-builder/$PLARFORM
        cat .config
        
    # || make V=s -j1  GL_PKGDIR=`pwd`/glinet4.x/$PLARFORM/
    # make -j2 GL_PKGDIR=`pwd`/glinet4.x/mt7981/ || 
    - name: 1.2 编译 
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        cd gl-infra-builder/$PLARFORM
        make -j$(nproc)  GL_PKGDIR=`pwd`/glinet4.x/$PLARFORM/ 
    
    - name:  failure  make -j1
      if: ${{ failure() }}
      run: |
        df -h
        cd gl-infra-builder/$PLARFORM
        make -j1  GL_PKGDIR=`pwd`/glinet4.x/$PLARFORM/ 
    
    - name:  df -h
      if: ${{ failure() }}
      run: |
        cd gl-infra-builder/$PLARFORM
        df -h
        du -ah -d1
        
    - name : 上传附件 target
      uses: actions/upload-artifact@master
      with:
        name: MT3000
        path: gl-infra-builder/mt7981/bin/
        if-no-files-found: error
        
  
